apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-router-port-forward
  namespace: kube-port-forward-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-router-port-forward
  template:
    metadata:
      labels:
        app: kube-router-port-forward
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: kube-router-port-forward
      containers:
        - name: kube-router-port-forward
          image: johrad/kube-router-port-forward
          imagePullPolicy: Always
          env:
            - name: UNIFI_USERNAME
              value: kube-port-forward-controller
            - name: UNIFI_ROUTER_IP
              value: 192.168.27.1
            - name: UNIFI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unifi-credentials
                  key: pass
            - name: DEBUG
              value: "True"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-router-port-forward
  namespace: kube-port-forward-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-router-port-forward
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-router-port-forward
subjects:
  - kind: ServiceAccount
    name: kube-router-port-forward
    namespace: kube-port-forward-controller
roleRef:
  kind: ClusterRole
  name: kube-router-port-forward
  apiGroup: rbac.authorization.k8s.io
