apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-port-forwarder
  namespace: unifi-port-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-port-forwarder
  template:
    metadata:
      labels:
        app: unifi-port-forwarder
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: unifi-port-forwarder
      containers:
        - name: unifi-port-forwarder
          image: johrad/unifi-port-forwarder
          imagePullPolicy: Always
          env:
            - name: UNIFI_USERNAME
              value: unifi-port-forwarder
            - name: UNIFI_ROUTER_IP
              value: 192.168.27.1
            - name: UNIFI_PASSWORD
              value: q4Fz\5#hdhaMHc.TL6UNMX+$
            - name: DEBUG
              value: "True"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unifi-port-forwarder
  namespace: unifi-port-forwarder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unifi-port-forwarder
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unifi-port-forwarder
subjects:
  - kind: ServiceAccount
    name: unifi-port-forwarder
    namespace: unifi-port-forwarder
roleRef:
  kind: ClusterRole
  name: unifi-port-forwarder
  apiGroup: rbac.authorization.k8s.io
