apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-port-forward
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-port-forward
  template:
    metadata:
      labels:
        app: unifi-port-forward
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: unifi-port-forward
      containers:
        - name: unifi-port-forward
          image: johrad/unifi-port-forward
          imagePullPolicy: Always
          env:
            - name: UNIFI_USERNAME
              value: unifi-port-forward
            - name: UNIFI_ROUTER_IP
              value: 192.168.1.1
            - name: UNIFI_PASSWORD
              value: password
            - name: DEBUG
              value: "True"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unifi-port-forward
  namespace: unifi-port-forward
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unifi-port-forward
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["unifi-port-forward.fiskhe.st"]
    resources: ["portforwardrules"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["unifi-port-forward.fiskhe.st"]
    resources: ["portforwardrules/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["unifi-port-forward.fiskhe.st"]
    resources: ["portforwardrules/finalizers"]
    verbs: ["update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unifi-port-forward
subjects:
  - kind: ServiceAccount
    name: unifi-port-forward
    namespace: unifi-port-forward
roleRef:
  kind: ClusterRole
  name: unifi-port-forward
  apiGroup: rbac.authorization.k8s.io
