apiVersion: v1
kind: Service
metadata:
  name: test-service9090-80
  namespace: unifi-port-forward
  labels:
  annotations:
    unifi-port-forward.fiskhe.st/mapping: "9090:http"
spec:
  selector:
    app: test
  ports:
    - port: 80
      name: http
      targetPort: 8080
  type: LoadBalancer
