apiVersion: v1
kind: Service
metadata:
  name: test-service801
  namespace: unifi-port-forwarder
  labels:
  annotations:
    unifi-port-forwarder/ports: "http:801"
spec:
  selector:
    app: test
  ports:
    - port: 801
      name: http
      targetPort: 8080
  # loadBalancerIP: 192.168.27.130
  type: LoadBalancer
