apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portforwardrule-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portforwardrule-controller
subjects:
- kind: ServiceAccount
  name: default
  namespace: default