apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portforwardrule-manager
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: portforwardrule-manager
subjects:
- kind: ServiceAccount
  name: default
  namespace: default