apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portforwardrule-manager
  namespace: unifi-port-forward
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: portforwardrule-manager
subjects:
  - kind: ServiceAccount
    name: unifi-port-forward
    namespace: unifi-port-forward
